import { Student } from "./types";

export const MOCK_STUDENTS: Student[] = [
  {
    id: "1",
    name: "Daniel Sarabia",
    year: "Year 12",
    avatar: "/images/latest-booking.png",
    preferredSchool: "Bristol University",
    ucatScore: "2640",
    aLevelScore: "AAA",
    category: "all",
  },
  {
    id: "2",
    name: "Emma Thompson",
    year: "Year 13",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Manchester",
    ucatScore: "2710",
    aLevelScore: "A*AA",
    category: "personal-statement",
  },
  {
    id: "3",
    name: "James Wilson",
    year: "Year 12",
    avatar: "/images/latest-booking.png",
    preferredSchool: "King's College London",
    ucatScore: "2580",
    aLevelScore: "AAA",
    category: "ucat",
  },
  {
    id: "4",
    name: "Sophie Chen",
    year: "Year 13",
    avatar: "/images/latest-booking.png",
    preferredSchool: "Imperial College London",
    ucatScore: "2850",
    aLevelScore: "A*A*A",
    category: "all",
  },
  {
    id: "5",
    name: "Oliver Martinez",
    year: "Year 12",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Birmingham",
    ucatScore: "2490",
    aLevelScore: "AAB",
    category: "personal-statement",
  },
  {
    id: "6",
    name: "Ava Johnson",
    year: "Year 13",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Edinburgh",
    ucatScore: "2720",
    aLevelScore: "A*AA",
    category: "ucat",
  },
  {
    id: "7",
    name: "Noah Anderson",
    year: "Year 12",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Leeds",
    ucatScore: "2610",
    aLevelScore: "AAA",
    category: "all",
  },
  {
    id: "8",
    name: "Isabella Brown",
    year: "Year 13",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Glasgow",
    ucatScore: "2680",
    aLevelScore: "AAA",
    category: "personal-statement",
  },
  {
    id: "9",
    name: "Liam Davies",
    year: "Year 12",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Nottingham",
    ucatScore: "2550",
    aLevelScore: "ABB",
    category: "ucat",
  },
  {
    id: "10",
    name: "Mia Roberts",
    year: "Year 13",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Oxford",
    ucatScore: "2900",
    aLevelScore: "A*A*A*",
    category: "all",
  },
  {
    id: "11",
    name: "Lucas Taylor",
    year: "Year 12",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Sheffield",
    ucatScore: "2620",
    aLevelScore: "AAA",
    category: "personal-statement",
  },
  {
    id: "12",
    name: "Charlotte Evans",
    year: "Year 13",
    avatar: "/images/latest-booking.png",
    preferredSchool: "University of Cambridge",
    ucatScore: "2880",
    aLevelScore: "A*A*A",
    category: "ucat",
  },
];
